---
- name: Add Helm Repository
  kubernetes.core.helm_repository:
    name: datadog
    repo_url: https://helm.datadoghq.com

- name: Update Helm
  ansible.builtin.shell: | 
    helm repo update

- name: Create Secret
  command: oc create secret generic datadog-secret --from-literal api-key=${{ dd_api_key_name }} --from-literal app-key=${{ dd_app_key_name }}
  tags: create_secret

- name: Download datadog file values.yaml
  get_url:
    url: "{{ url_file_values }}"
    dest: /home/lab-user/
  tags: download_file

- name: Install Datadog Agent
  ansible.builtin.shell: | 
    helm install datadog-monitor \
    -f /home/lab-user/values-clusteragent-full.yaml \
    --set targetSystem=linux \ 
    datadog/datadog
  tags: install_agent